### ISSUE TITLE
UE to Rigify - Incorrect rig setup leads to importing issues in UE5

### ISSUE THREAD

**Issue by Alfier** [poly-hammer/BlenderTools#23]
Addon: UE to Rigify

    Steps to Reproduce the Problem: import UE5 male mannequin FBX skeletal mesh, select root source from 3D view, use "Male Mannequin Ue5" template, click convert. Try to export the result in Unreal Engine.
    Error Log: no error logs
    OS: Windows 10
    Addon Version: UE2Rigify 1.6.4
    Blender Version: Blender 3.6 / 4.1
    Unreal Version: Unreal 5.4.2

The default mannequin templates are straight up incompatible with Unreal Engine.
Trying to import in UE the pic's first setup results in error **"Multiple roots are found in the bone hierarchy. We only support single root bone."** since the root bone is not correctly exported from the Unreal Engine skeletal mesh and, therefore, all the bones under it are placed at the same level. The import completely fails this way.

This issue could be solved adding a new root bone and reparenting everything else to it, like in the pic's second setup.
This way, though, the rig doesn't match the mannequin template, since it consider the "pelvis" bone as the root, unlike Unreal's mannequin that has the root bone set to the... root bone. Therefore the UE to Rigify conversion fails. No log error is shown, the convert button simply does nothing.

Unfortunately blender imports the root bone as the armature root, that is not an actual bone from its point of view, leading to this chain of issues.

![UE2Rigify_IncorrectSetup](https://github.com/poly-hammer/BlenderTools/assets/15878566/8b196187-1609-4954-86ce-41821d0fa80b)

**Comment by jack-yao91** [comment]
Have you tried with this option on and off?
https://poly-hammer.github.io/BlenderTools/send-to-unreal/settings/export/#export-object-name-as-root-bone

**Comment by Alfier** [comment]
> Have you tried with this option on and off? https://poly-hammer.github.io/BlenderTools/send-to-unreal/settings/export/#export-object-name-as-root-bone

Yep, it's checked by default but exporting to unreal still returns that error

**Comment by JoshQuake** [comment]
Is this with the use of Send2UE to export to unreal?

I cant replicate this issue 🤔. However I did run into a different issue on Blender's side when trying to send assets while in ue2rigify's Control mode. I'll create a different issue to track that though.

**Comment by Alfier** [comment]
Also, trying to bake a simple animation to the source rig and then exporting with Send2UE, this error is returned along with the usual error log in UE

```
Python: Traceback (most recent call last):
  File "F:\script_addon_cust\addons\send2ue\dependencies\rpc\factory.py", line 221, in run_function_remotely
    return remote_function(*args)
  File "C:\Blender Foundation\Blender 3.6\3.6\python\lib\xmlrpc\client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "C:\Blender Foundation\Blender 3.6\3.6\python\lib\xmlrpc\client.py", line 1464, in __request
    response = self.__transport.request(
  File "C:\Blender Foundation\Blender 3.6\3.6\python\lib\xmlrpc\client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Blender Foundation\Blender 3.6\3.6\python\lib\xmlrpc\client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "C:\Blender Foundation\Blender 3.6\3.6\python\lib\xmlrpc\client.py", line 1354, in parse_response
    return u.close()
  File "F:\script_addon_cust\addons\send2ue\dependencies\rpc\client.py", line 63, in close
    raise exception(exception_message)
RuntimeError: The /Game/untitled_category/untitled_asset/SKM_Manny_LOD0_Skeleton does not exist in the project!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\script_addon_cust\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "F:\script_addon_cust\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "F:\script_addon_cust\addons\send2ue\core\ingest.py", line 26, in import_asset
    UnrealRemoteCalls.import_asset(file_path, asset_data, property_data)
  File "F:\script_addon_cust\addons\send2ue\dependencies\rpc\factory.py", line 248, in wrapper
    return rpc_factory.run_function_remotely(function, args)
  File "F:\script_addon_cust\addons\send2ue\dependencies\rpc\factory.py", line 226, in run_function_remotely
    raise exception.__class__(stack_trace).with_traceback(call_traceback)
  File "F:\script_addon_cust\addons\send2ue\core\ingest.py", line 26, in import_asset
    UnrealRemoteCalls.import_asset(file_path, asset_data, property_data)
RuntimeError: The /Game/untitled_category/untitled_asset/SKM_Manny_LOD0_Skeleton does not exist in the project!  File "F:\script_addon_cust\addons\send2ue\dependencies\unreal.py", line 1244
```
![MultipleRoots](https://github.com/poly-hammer/BlenderTools/assets/15878566/585a7124-4bba-4ac6-ad95-8d4afbe9d879)

**Comment by JoshQuake** [comment]
I'm installing 5.4 and seeing if for some reason something changed with the mannequins because I'm unable to replicate this with a default 5.2 ue5 manny. I will update when I have time to take a look.

**Comment by JoshQuake** [comment]
Can you please send the blend file and your send2UE settings? You can save a template and upload here.

I've reconfirmed no issue with unreal 5.4 mannequin and resolved #24 to export while in Control mode and still no issue.

![image](https://github.com/poly-hammer/BlenderTools/assets/3147154/cc35a5de-3d11-4ebc-ae3d-a8f7f100922f)

**Comment by Alfier** [comment]
You can find both files [here](https://we.tl/t-8J5L9oc4iB).
However the template is the default one, minus the "Check scene scale" checkbox.

**Comment by JoshQuake** [comment]
I still didn't get those errors lol, but there is definitely something wrong with your mannequin.
![image](https://github.com/poly-hammer/BlenderTools/assets/3147154/e9506e41-9575-4cd0-9ed7-4b95f8f49636)

Issue could be a mismatch in your path settings? I think there probably would've been an error about permissions but maybe permission issue with unreal directory? Also try deleting previous broken assets in unreal before pushing again.

Here's the default ue5.4 mannequin exported from a fresh install 
[SKM_Manny.zip](https://github.com/user-attachments/files/15981047/SKM_Manny.zip)

and my typical process of sending a ue2rigify rig. I switch back to Source only to avoid a separate issue now fixed for next release #24.

https://github.com/poly-hammer/BlenderTools/assets/3147154/d6b5a091-9e2f-467a-92c7-21d809e83d22

**Comment by Alfier** [comment]
The results are the same even with your manny.fbx
I don't think it can't be anything other than a weird Send2UE bug, since if I rearrange the armature hierarchy this way
![UE2Rigify_CorrectSetup](https://github.com/poly-hammer/BlenderTools/assets/15878566/9683b97b-1322-4813-83f8-391238a9c713)
the export succeed (even if the mesh is broken as in your pic).

**Comment by Alfier** [comment]
Seems that the weird deformed skeletal mesh happens due to the blender units.
Usually I set metric 0.01 unit scale working with unreal. When I switched to the following settings the exported mesh was fine
![Units](https://github.com/poly-hammer/BlenderTools/assets/15878566/dfef2653-233c-4b5e-b749-680fc7af952b)
![Immagine 2024-06-26 185014](https://github.com/poly-hammer/BlenderTools/assets/15878566/d285e605-b7fc-4edb-8f7f-555b7dc8e9a4)

I can't understand why though. And unfortunately I can't fully work with Blender 4.1 due to various not compatible addons

**Comment by JoshQuake** [comment]
Thanks for the updated info. I shall keep looking for possible causes.

**Comment by jack-yao91** [comment]
Kinda wierd this happened. At least with default settings, there is a validation that runs to check that your scene scale is set to 1. 
https://poly-hammer.github.io/BlenderTools/send2ue/settings/validations/#check-scene-scale

Unless that validation was turned off, it shouldve given a error pop up. @JoshQuake @Alfier looks like scene scale 1 is the resolution, can this be closed?
