### ISSUE TITLE
Send2Unreal: Crash on Send

### ISSUE THREAD

**Issue by DanMcLaughlin** [poly-hammer/BlenderTools#45]
* **Addon:**  Send to Unreal
* **Steps to Reproduce the Problem:** I clicked Pipeline > Export > Send to Unreal
* **Error Log:** 
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\export.py", line 224, in export_mesh
    # run the pre mesh export extensions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 950, in select_asset_collisions

  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 636, in get_asset_collisions
    if is_collision_of(asset_name, mesh_object.name, properties):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 832, in is_collision_of
    return bool(
             ^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.0.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\re\__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.0.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.0.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.0.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.0.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.2.0.0_x64__ppwjx1n5r4v9t\Blender\4.2\python\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 44
```

* **OS:** Windows
* **Addon Version:** Send to Unreal 2.4.5
* **Blender Version:** Blender 4.2
* **Unreal Version:** Unreal 5.2

**Comment by DanMcLaughlin** [comment]
Wups my mistake, this is the old regex error, I brought up an old file that still had that in the prefs

**Comment by namrog84** [comment]
@DanMcLaughlin hey, I'm facing this issue suddenly and not sure what.  What 'regex error' did you have or should I check?

**Comment by DanMcLaughlin** [comment]
From memory, go to the Import tab, look at the LOD import which has a text entry for regex name search, delete “(!?)” IIRC

**Comment by JoshQuake** [comment]
I know this is closed but just for clarity, (?i) is properly supported now so no need to remove it. However I believe that's the only global flag detected right now so if other flags are used it will probably come up with this error.
