### ISSUE TITLE
Send2UE: Export failure 

### ISSUE THREAD

**Issue by DanMcLaughlin** [poly-hammer/BlenderTools#83]
* **Addon:** iSend to Unreal
* **Steps to Reproduce the Problem:** I clicked Pipeline > Export > Send to Unreal
* **Error Log:** 
```
AttributeError: 'NoneType' object has no attribute 'name'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\operators.py", line 91, in invoke
    self.pre_operation()
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\operators.py", line 160, in pre_operation
    extension.run_extension_tasks(ExtensionTasks.PRE_OPERATION.value)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\core\extension.py", line 76, in run_extension_tasks
    task(*args)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\resources\extensions\affixes.py", line 326, in pre_operation
    add_affixes()
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\resources\extensions\affixes.py", line 45, in add_affixes
    rename_all_textures(texture_images, append_affix, properties)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\resources\extensions\affixes.py", line 170, in rename_all_textures
    new_name = affix_operation(image, properties.extensions.affixes.texture_name_affix, is_image=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\send2ue\resources\extensions\affixes.py", line 99, in append_affix
    filename, ext = os.path.splitext(scene_object.name)
                                     ^^^^^^^^^^^^^^^^^
```

* **OS:** Windows
* **Addon Version:** Send to Unreal 2.4.9
* **Blender Version:** Blender 4.2.1 LTS
* **Unreal Version:** Unreal 5.4

Spinning around this I don't see it being an issue with my model but that's possible, I have no textures in the model. Why is rename_all_textures being called?

**Comment by DanMcLaughlin** [comment]
Apologies, solved there was a texture material.
